### PR TITLE
Fix printing wine version with custom WINELOADER

### PR DESCRIPTION
**Pull request by MetaDark**
Hi, I noticed that when specifying `WINELOADER`, the wine version being printed was `<NOT FOUND>`. This commit just ensures the behaviour is equivalent to what happens in the generated exe wrappers:

- Don't call `bp::search_path` when using `WINELOADER`. It will return an empty string for anything that's not in `PATH`.
- To match the behaviour of the exe wrapper scripts, only print the wine version from `WINELOADER` if the path is executable.

### CODE REVIEW

**Comment by robbert-vdh** [comment]
Good catch, thanks! Coincidentally I was actually wondering whether this worked or not earlier today, and I also found out that it wasn't working when I was doing a bisect of Wine to figure out which commit between Wine 6.6 and Wine 6.7 broke Spitfire.

**Comment by robbert-vdh** [comment]
Whoops, well, I forgot that the CI doesn't run by default on pull requests :sweat_smile:. I fixed the type error in 93df3fa1da6ffcc69a5b384ba04e3da7c5ef23ef.

**Comment by MetaDark** [comment]
Oh weird, it compiled and worked on my machine. Maybe there's a difference with the boost version used in CI?

**Comment by robbert-vdh** [comment]
I'm using Boost 1.75 on both my machine and on the CI. Maybe your version does an implicit conversion from paths back to strings without having to call `.string()`? I don't think Boost.Filesystem ever did such a thing, but you never know!

**Pull request merged**
