### PR TITLE
Clarify that yabridgectl isn't a standalone thing

### PR DESCRIPTION
**Pull request by eoghanmurray**
I'm just remembering that this was confusing to me the first time;
it was recommending a 'simpler' way of doing things through yabridgectl.  I didn't understand that that was a wrapper around the underlying yabridge.

Could you just package them together as a single 'yabridge' download? 
i.e. do you have users who want yabridge but not yabridgectl?

### CODE REVIEW

**Comment by robbert-vdh** [comment]
I've seen a surprising amount of people who want to manually make copies or script their own installation procedure instead of using yabridgectl. The download for yabridgectl is also not distro dependent like the yabridge archives are, and since they're completely separate code bases written in different programming languages they're also built independently of each other.

**Comment by cameronleger** [comment]
> I've seen a surprising amount of people who want to manually make copies or script their own installation procedure instead of using yabridgectl.

I'm one and allow me to explain. WINE VST Wrappers are not new to me, so I already had an existing workflow that worked well for me. yabridgectl doesn't support that workflow, so it's a hurdle to refactor my ways. What I have amounts to 9 verbose lines of bash that I wrote/diagnosed, so I trust them. So, there's costs but no good reasons to swap for me.

First, I have many wineprefixes, and _where_ the VSTs are seems to be pretty different across and within them; so, I have one WINE-VST related folder somewhere in my home-directory. For every DLL that I want to use, a simple `ybcp <file>` copies yabridge next to that DLL, then symlinks that SO into my own folder. So, I have one folder with tons of links reaching out to files across drives/directories. Another simple `ybu` copies yabridge to the location pointed to by all of those symlinks.

KISS; there's no state management, no configuration, just copying/symlinking/following files.

**Comment by eoghanmurray** [comment]
I'm mainly just recommending that there is a single download that includes both yabridgectl and yabridge, so I don't have to understand all this the first time round.

That shouldn't affect existing workflows (except that they also now download yabridgectl which they won't use)

**Comment by robbert-vdh** [comment]
I personally feel like the readme is clear in this regard, and I have not had any other people mention that they found this confusing. Only thing that sometimes goes wrong is that from time to time people running Debian will download the wrong archive instead of the `-ubuntu-18.04.tar.gz` version, but that wouldn't be solved by a packaging change like this. The binaries on the releases page are coming straight from the CI and I don't touch them at all. I could edit them to add in the yabridgectl binary and I might do that at some point, but that will then probably be combined with some other restructuring in preparation for VST3 support.

**Comment by robbert-vdh** [comment]
Since setting up VST3 plugins without yabridgectl is unsupported, the yabridgectl binary is now merged into the regular yabridge release archives on the GitHub releases page as of yabridge 3.0.0. Thanks for the suggestion!

**Pull request closed without merging**
